# Quick Thumbnails Preset
# Fast thumbnail generation for quick previews

name: quick-thumbnails
description: "Generate small PNG thumbnails quickly for preview purposes"
base_workflow: pdf-to-web

# Override settings for speed and smaller size
overrides:
  settings:
    parallel_jobs: 8  # More parallel processing for speed

  steps:
    create_thumbnails:
      params:
        width: 150
        height: 100
        # Note: Produces PNG thumbnails with white background (no quality param needed for PNG)

    create_full_size:
      # Skip full-size creation for quick mode
      enabled: false

    generate_gallery_html:
      # Skip gallery generation since no full-size images exist
      enabled: false

# Output: PNG thumbnails only (no gallery.html)
# Use cases:
# - Quick PDF preview generation
# - Batch processing where speed is priority over quality
# - Initial content review before full processing
